### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by mario-s** [ChristophAl/skin_cancer#1]
I followed the setup as described in the readme. However I still have an error, even on a POSIX environment. Is the readme correct? Or is there a problem when loading the model?

$python3 app.py
Using TensorFlow backend.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "app.py", line 37, in <module>
    main()
  File "app.py", line 27, in main
    classifier = MelanomaClassifier(config)
  File "/Users/XXX/develop/projects/skin_cancer/src/classification/NNClassifier.py", line 14, in __init__
    self._model = self.create_model()
  File "/Users/XXX/develop/projects/skin_cancer/src/classification/NNClassifier.py", line 35, in create_model
    model.load_weights(config.weights_path)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 2702, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-z0d9zbgm-build/h5py/_objects.c:2853)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-z0d9zbgm-build/h5py/_objects.c:2811)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-z0d9zbgm-build/h5py/h5f.c:2099)
OSError: Unable to open file (File signature not found)

**Comment by ChristophAl** [comment]
This happens when the model.h5 file is not properly synced via git lfs.
We had this issue several times today.
First, install git-lfs with: brew install git-lfs, then do git lfs install, followed by git lfs pull which is then actually downloading the model file.

**Comment by mario-s** [comment]
Yeah, cool. It solved the problem. I will add it to the readme.
